apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: hello
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/solstice-api-junkyard/hello
deploy:
  kubectl:
    manifests:
    - k8s.yaml
