on: push
name: Build and Deploy to GKE

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: nmandad
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: hello
  IMAGE: hello

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: |-
        gcloud --quiet auth configure-docker

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    - name: Apply manifest
      uses: actions-hub/kubectl@master
      with:
        args: apply -f k8s.yaml

    - name: Update the image name
      uses: steebchen/kubectl@v1.0.0
      with:
        args: set image deployment/$DEPLOYMENT_NAME $IMAGE=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

    - name: Update the image name
      uses: steebchen/kubectl@v1.0.0
      with:
        args: rollout restart deployment/$DEPLOYMENT_NAME
